version: '3.1'
services:
    db:
        image: postgres
        container_name: square_database
        restart: always
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=square
        ports: 
            - 5432:5432
    admin:
        image: adminer
        container_name: square_admin
        restart: always
        links: 
            - db
        ports:
            - 8080:8080
        depends_on:
            - db
